# Generated by Django 4.2.5 on 2023-10-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shader',
            name='pub_date',
        ),
    ]
